optimumerp/clients/urls.py
from django.urls import path
from . import views

app_name = "clients"

urlpatterns= [
    path("", views.index, name="index"),
    path("<int:id>/toggle_enabled", views.toggle_enabled, name="toggle_enabled"),
    path("<int:id>/delete/", views.delete, name="delete"),
    path("cadastro/", views.create, name="create"),
    path("<slug:slug>/", views.ClientsUpdateView.as_view(), name="update"),
]

optimumerp/optimumerp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedores/', include('suppliers.urls')),
    path('produtos/', include("products.urls")),
    path('transacoes/', include("transactions.urls")),
    path('estoque/', include("inventory.urls")),
    path("clientes/", include("clients.urls")),
    path("pedidos-de-venda/", include("sales_order.urls")),
    path('', include('users.urls')),
    path('nota-fiscal/', include('invoices.urls')),
    path("pedidos-de-compras/", include("purchases.urls")),
    path('empresa/', include("company.urls")),
    path('dashboard/', include('dashboard.urls')),
    path('categorias/', include("categories.urls"))
]

optimumerp/users/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views
from .views import UserLoginView, UserLogoutView, EmployeeCreateView

app_name = 'users'
urlpatterns = [
    path("", RedirectView.as_view(url="/login/", permanent=True)),
    path('usuarios/', views.index, name="index"),
    path("usuarios/cadastro/", EmployeeCreateView.as_view(), name="create"),
    path('login/', UserLoginView.as_view(), name="login"), 
    path('usuarios/<str:name>/', views.update, name="update"),
    path('usuarios/<int:id>/delete', views.delete, name="delete"),
    path('logout/', UserLogoutView.as_view(), name="logout"),
]

optimumerp/clients/models.py
from django.db import models
from django.utils.text import slugify


class Clients(models.Model):
    """
    Modelo que representa um cliente.

    Este modelo contém informações sobre os clientes, incluindo seu nome empresarial, nome fantasia, CNPJ, e-mail,
    endereço, telefone, entre outros.

    Attributes:
        STATE_CHOICES (dict): Um dicionário que mapeia os códigos de estado do Brasil para seus respectivos nomes.
        company_name (str): Nome empresarial do cliente.
        fantasy_name (str): Nome fantasia do cliente.
        slug (str): Slug utilizado para URLs amigáveis.
        representative (str): Nome do representante do cliente.
        cnpj (str): CNPJ (Cadastro Nacional da Pessoa Jurídica) do cliente.
        email (str): Endereço de e-mail do cliente.
        zipcode (str): CEP (Código de Endereçamento Postal) do cliente.
        street (str): Nome da rua do endereço do cliente.
        number (str): Número do endereço do cliente.
        city (str): Nome da cidade do endereço do cliente.
        state (str): Estado do endereço do cliente, representado por um código de duas letras.
        phone (str): Número de telefone do cliente.
        enabled (bool): Indica se o cliente está ativo ou inativo.
        created_at (datetime): Data e hora de criação do registro do cliente.

    Methods:
        __str__(): Retorna uma representação de string do nome empresarial do cliente.
        __repr__(): Retorna uma representação de string do nome empresarial do cliente.
        save(*args, **kwargs): Sobrescreve o método save() para gerar o slug do cliente antes de salvar no banco de dados.

    Meta:
        verbose_name (str): Nome singular do modelo, utilizado no admin do Django.
        verbose_name_plural (str): Nome plural do modelo, utilizado no admin do Django.
    """

    STATE_CHOICES = {
        "AC": "Acre", 
        "AL": "Alagoas", 
        "AP": "Amapá", 
        "AM": "Amazonas", 
        "BA": "Bahia", 
        "CE": "Ceará",
        "ES": "Espírito Santo", 
        "GO": "Goiás", 
        "MA": "Maranhão", 
        "MT": "Mato Grosso", 
        "MS": "Mato Grosso do Sul",
        "MG": "Minas Gerais", 
        "PA": "Pará", 
        "PB": "Paraíba", 
        "PR": "Paraná", 
        "PE": "Pernambuco", 
        "PI": "Piauí",
        "RJ": "Rio de Janeiro", 
        "RN": "Rio Grande do Norte", 
        "RS": "Rio Grande do Sul", 
        "RO": "Rondônia",
        "RR": "Roraima", 
        "SC": "Santa Catarina", 
        "SP": "São Paulo", 
        "SE": "Sergipe", 
        "TO": "Tocantins",
        "DF": "Distrito Federal",
    }
    
    company_name = models.CharField(max_length=255)
    fantasy_name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True, blank=True)
    representative = models.CharField(max_length=255)
    cnpj = models.CharField(max_length=20)
    email = models.EmailField(unique=True)
    zipcode = models.CharField(max_length=20)
    street = models.CharField(max_length=255)
    number = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=2, choices=STATE_CHOICES)
    phone = models.CharField(max_length=255)
    enabled = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        """
        Retorna uma representação de string do nome empresarial do cliente.
        
        Returns:
            str: Nome empresarial do cliente.
        """
        return self.company_name

    def __repr__(self):
        """
        Retorna uma representação de string do nome empresarial do cliente.

        Returns:
            str: Nome empresarial do cliente.
        """
        return self.company_name
    
    def save(self, *args, **kwargs):
        """
        Sobrescreve o método save() para gerar o slug do cliente antes de salvar no banco de dados.

        Args:
            *args: Argumentos posicionais adicionais.
            **kwargs: Argumentos de palavra-chave adicionais.
        """
        self.slug = slugify(self.fantasy_name)
        super(Clients, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"

optimumerp/clients/forms.py
import re
from django import forms
from .models import Clients


class ClientsForm(forms.ModelForm):
    """
    Este formulário é utilizado para criar ou atualizar informações de clientes, incluindo razão social, nome fantasia,
    CNPJ, e-mail, endereço, telefone, entre outros.

    Attributes:
        Meta (nested class): Define os metadados do formulário, incluindo o modelo associado, os campos a serem excluídos,
            os rótulos dos campos e mensagens de erro personalizadas.

    Methods:
        clean_cnpj(): Limpa e formata o CNPJ, removendo caracteres não numéricos.
        clean_phone(): Limpa e formata o número de telefone, removendo caracteres não numéricos.
        clean_zipcode(): Limpa e formata o CEP, removendo caracteres não numéricos.
    """

    class Meta:
        """
        Metadados do formulário.

        Attributes:
            model (Model): O modelo associado ao formulário.
            exclude (list): Lista de campos a serem excluídos do formulário.
            labels (dict): Dicionário que mapeia os nomes dos campos para rótulos personalizados.
            error_messages (dict): Dicionário que define mensagens de erro personalizadas para campos específicos.
        """
        model = Clients
        exclude = ["slug"]
        
        labels = {
            "company_name": "Razão Social",
            "fantasy_name": "Nome fantasia",
            "representative": "Representante",
            "cnpj": "CNPJ",
            "email": "E-mail",
            "zipcode": "CEP",
            "street": "Rua",
            "number": "Número",
            "city": "Cidade",
            "state": "Estado",
            "phone": "Contato",
            "enabled": "Ativo"
        }
        
        error_messages = {
            "fantasy_name": { 
                "unique": "O fornecedor com esta razão social já está cadastrado",
                "max_length": "Limite de 255 caracteres.",
                "required": "O campo é obrigatório",
            },
            "email": {
                "unique": "Já existe um fornecedor com este e-mail."
            }
        }

    def clean_cnpj(self):
        """
        Limpa e formata o CNPJ, removendo caracteres não numéricos.

        Returns:
            str: CNPJ formatado.
        """
        cnpj = self.cleaned_data.get("cnpj", "")
        cnpj = re.sub("[^0-9]", "", cnpj)
        
        return cnpj
    
    def clean_phone(self):
        """
        Limpa e formata o número de telefone, removendo caracteres não numéricos.

        Returns:
            str: Número de telefone formatado.
        """
        phone = self.cleaned_data.get("phone", "")
        phone = re.sub("[^0-9]", "", phone)

        return phone

    def clean_zipcode(self):
        """
        Limpa e formata o CEP, removendo caracteres não numéricos.

        Returns:
            str: CEP formatado.
        """
        zipcode = self.cleaned_data.get("zipcode", "")
        zipcode = re.sub("[^0-9]", "", zipcode)

        return zipcode

optimumerp/clients/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from .forms import ClientsForm
from .models import Clients
from django.core.paginator import Paginator
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.views.generic import UpdateView
from sales_order.models import SalesOrder
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .filters import ClientsFilter

@login_required
def index(request):
    """
    View para exibir uma lista paginada de clientes e aplicar filtros.

    Retorna uma página HTML contendo uma lista paginada de clientes, com a opção de filtrar os clientes
    por diversos critérios.

    Args:
        request (HttpRequest): Requisição HTTP recebida pelo servidor.

    Returns:
        HttpResponse: Resposta HTTP contendo a página HTML com a lista de clientes e filtros aplicados.

    """
    clients = Clients.objects.order_by("-id")
    client_filter = ClientsFilter(request.GET, queryset=clients)

    paginator = Paginator(client_filter.qs, 3)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        "page_obj": page_obj,
        'filter': client_filter
    }
    
    return render(request, "clients/index.html", context)


class ClientsUpdateView(UpdateView):
    """
    View para atualizar informações de um cliente existente.

    Permite que um usuário atualize informações de um cliente existente por meio de um formulário HTML.
    Verifica se o cliente está associado a pedidos de vendas pendentes antes de inativá-lo.

    Attributes:
        model (Clients): Modelo do cliente a ser atualizado.
        template_name (str): Nome do template HTML a ser usado para renderizar a página.
        form_class (form): Classe do formulário a ser usado para processar os dados do cliente.
        success_url (str): URL para redirecionar o usuário após uma atualização bem-sucedida.

    Methods:
        form_valid(self, form): Executado quando o formulário é válido, verifica se há pedidos de vendas pendentes antes de inativar o cliente e envia uma mensagem de sucesso.
        form_invalid(self, form): Executado quando o formulário é inválido, envia uma mensagem de erro.

    """
    model = Clients
    template_name = "clients/update.html"
    form_class = ClientsForm
    success_url = reverse_lazy("clients:index")

    def form_valid(self, form):
        """
        Executado quando o formulário é válido.

        Verifica se há pedidos de vendas pendentes associados ao cliente antes de inativá-lo e envia uma mensagem de sucesso.

        Args:
            form (Form): Formulário contendo os dados atualizados do cliente.

        Returns:
            HttpResponse: Resposta HTTP após a atualização bem-sucedida do cliente.

        """
        client = form.instance
        pending_sale_order = SalesOrder.objects.filter(client=client, status="Pendente").aggregate(count=Count('id'))['count']
        if pending_sale_order > 0 and not client.enabled:
            messages.error(self.request, f"Não foi possível inativar o cliente, pois o mesmo está associado a um pedido de vendas pendente.")
            return super().form_invalid(form)

        response = super().form_valid(form)
        messages.success(self.request, "Cliente atualizado com sucesso!")
        return response

    def form_invalid(self, form):
        """
        Executado quando o formulário é inválido.

        Envia uma mensagem de erro após uma tentativa malsucedida de atualizar o cliente.

        Args:
            form (Form): Formulário contendo os dados do cliente.

        Returns:
            HttpResponse: Resposta HTTP após uma tentativa malsucedida de atualizar o cliente.

        """
        response = super().form_invalid(form)
        messages.error(self.request, "Erro ao atualizar o cliente!")
        return response


@require_POST
def toggle_enabled(request, id):
    """
    View para ativar ou desativar um cliente.

    Ativa ou desativa um cliente com base no ID fornecido na requisição.
    Verifica se há pedidos de vendas pendentes associados ao cliente antes de inativá-lo.

    Args:
        request (HttpRequest): Requisição HTTP recebida pelo servidor.
        id (int): ID do cliente a ser ativado ou desativado.

    Returns:
        JsonResponse: Resposta JSON indicando o resultado da operação.

    """
    client = get_object_or_404(Clients, pk=id)

    pending_sale_order = SalesOrder.objects.filter(client=client, status="Pendente").aggregate(count=Count('id'))['count']
    if pending_sale_order > 0:
        messages.error(request, f"Não foi possível inativar o cliente, pois o mesmo está associado a um pedido de vendas pendente.")
        return JsonResponse({ "message": "error" })

    client.enabled = not client.enabled
    client.save()

    return JsonResponse({ "message": "success"})

@require_POST
def delete(request, id):
    """
    View para excluir um cliente.

    Exclui um cliente com base no ID fornecido na requisição.
    Verifica se há pedidos de vendas associados ao cliente antes de excluí-lo.

    Args:
        request (HttpRequest): Requisição HTTP recebida pelo servidor.
        id (int): ID do cliente a ser excluído.

    Returns:
        HttpResponseRedirect: Redireciona o usuário de volta para a página anterior após a exclusão bem-sucedida do cliente.

    """
    client = get_object_or_404(Clients, pk=id)
    
    sale_order_count = SalesOrder.objects.filter(client=client).aggregate(count=Count('id'))['count']
    if sale_order_count > 0:
        messages.error(request, f"Não foi possível excluir o cliente, pois o mesmo já está associado a um pedido de vendas. Considere inativá-lo.")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    
    client.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def create(request):
    """
    View para criar um novo cliente.

    Exibe um formulário HTML para o usuário preencher com os dados do novo cliente.
    Após o envio do formulário, processa os dados e cria o novo cliente.

    Args:
        request (HttpRequest): Requisição HTTP recebida pelo servidor.

    Returns:
        HttpResponse: Resposta HTTP contendo o formulário para criar um novo cliente.

    """
    #POST
    if request.method == "POST":
        form = ClientsForm(request.POST)
        
        if form.is_valid():
            form.save()

            messages.success(request, "Cliente cadastrado com sucesso!")
            return redirect("clients:index")


        messages.error(request, "Falha ao cadastrar o cliente. Verifique o preenchimento dos campos")
        context = { "form": form }        
        return render(request, "clients/create.html", context)
    
    #GET
    form = ClientsForm()
    context = { "form": form }
    return render(request, "clients/create.html", context)

optimumerp/clients/templates/clients/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Cadastro de Clientes
{% endblock %}
{% block head %}
  <link rel="stylesheet" href="{% static 'clients/css/createUpdate.css' %}" />

  <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="{% static 'clients/js/createUpdate.js' %}"></script>
{% endblock %}

{% block page_name %}
  Cadastro de Cliente
{% endblock %}

{% block search %}
  {% comment %}Sem search{% endcomment %}
  <div style="height: 38px;"></div>
{% endblock %}

{% block content %}
  <form method="post" novalidate enctype="multipart/form-data">
    {% csrf_token %}

    <div class="d-flex create-client p-3 flex-column">
      {% include 'partials/_client_form.html' %}
      <div class="d-grid">
        <button class="btn btn-primary btn-lg">Salvar</button>
      </div>
    </div>
  </form>
{% endblock %}

optimumerp/clients/templates/clients/index.html
{% extends "base.html" %}
{% load static %}
{% load phone_filter %}
{% load crispy_forms_tags %}
{% block title %}Clientes{% endblock  %}

{% block head %}
<link rel="stylesheet" href="{% static 'clients/css/index.css' %}">

<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
<script src="{% static 'base/js/index.js' %}"></script>
{% endblock  %}

{% block page_name %}Clientes{% endblock %}

{% block search %}
  {% comment %}Sem search{% endcomment %}
  <div style="height: 38px;"></div>
{% endblock %}

{% block content %}

<div class="row container-fluid">
  <div class="col-md-2">
    <a 
      href="{% url "clients:create" %}" title="Cadastrar novo cliente"
      class="btn btn-success">
      <i class="bi bi-plus"></i>
      Novo
    </a>
  </div>
</div>

<div class="row d-flex mt-2 container-fluid">
  <div class="col-md-3">
    {% include "partials/_filter.html" with main_page="clients:index" %}
  </div>


  <div class="table-responsive bg-white p-2 col-md-9 rounded" style="height:80vh">
    <table class="table table-borderless table-hover table-sm table-color">
      <thead class="table-border">
        <tr>
          <th>Ações</th>
          <th>ID</th>
          <th>Razão Social</th>
          <th>Nome Fantasia</th>
          <th>Representante</th>
          <th>Telefone</th>
          <th>Ativo</th>
        </tr>
      </thead>
      <tbody>
        {% for client in page_obj %}
          <tr>
            <td class="d-flex gap-1">
              <a href="{% url 'clients:update' client.slug %}" class="btn btn-warning btn-sm" title="editar cliente"><i class="bi bi-pencil"></i></a>
              <form method="post" action="{% url 'clients:delete' client.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm" title="remover cliente"><i class="bi bi-trash"></i></button>
              </form>
            </td>
            <td>{{ client.id }}</td>
            <td>{{ client.company_name|title }}</td>
            <td>{{ client.fantasy_name|title }}</td>
            <td>{{ client.representative|title }}</td>
            <td>{{ client.phone|format_phone }}</td>
            <td>
              <input {% if client.enabled %}checked{% endif %} data-url="{% url 'clients:toggle_enabled' client.id %}" type="checkbox" class="form-check-input" />
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="8" class="text-center">Nenhum cliente cadastrado</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
  {% include "partials/_paginator.html" %}
</div>
{% endblock  %}

optimumerp/clients/templates/clients/update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Edição de Clientes
{% endblock %}
{% block head %}
  <link rel="stylesheet" href="{% static 'clients/css/createUpdate.css' %}" />

  <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="{% static 'clients/js/createUpdate.js' %}"></script>
{% endblock %}

{% block page_name %}
  Atualizar cliente
{% endblock %}

{% block search %}
  {% comment %}Sem search{% endcomment %}
  <div style="height: 38px;"></div>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}

    <div class="d-flex create-clients m-3 flex-column">
      {% include 'partials/_client_form.html' %}
      <div class="d-grid">
        <button class="btn btn-primary btn-lg">Salvar</button>
      </div>
    </div>
  </form>
{% endblock %}