optimumerp/optimumerp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedores/', include('suppliers.urls')),
    path('produtos/', include("products.urls")),
    path('transacoes/', include("transactions.urls")),
    path('estoque/', include("inventory.urls")),
    path("clientes/", include("clients.urls")),
    path("pedidos-de-venda/", include("sales_order.urls")),
    path('', include('users.urls')),
    path('nota-fiscal/', include('invoices.urls')),
    path("pedidos-de-compras/", include("purchases.urls")),
    path('empresa/', include("company.urls")),
    path('dashboard/', include('dashboard.urls')),
    path('categorias/', include("categories.urls"))
]

optimumerp/purchases/urls.py
from django.urls import path
from . import views

app_name = "purchases"

urlpatterns = [
    path("", views.index, name="index"),
    path("novo/get_purchasing_price/", views.get_purchasing_price_create, name="get_purchasing_price_create"),
    path("editar/<int:id>/get_purchasing_price/", views.get_purchasing_price_update, name="get_purchasing_price_update"),
    path("novo/", views.create, name="create"),
    path("editar/<int:id>/", views.update, name="update"),
    path("<int:id>/delete_product", views.delete_product_from_purchase, name="delete_product"),
    path("<int:id>/products/", views.get_products_from_purchase, name="products"),
    path("<int:id>/cancel/", views.cancel, name="cancel"),
    path("<int:id>/finish-order/", views.finish_order, name="finish_order")
]

optimumerp/users/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views
from .views import UserLoginView, UserLogoutView, EmployeeCreateView

app_name = 'users'
urlpatterns = [
    path("", RedirectView.as_view(url="/login/", permanent=True)),
    path('usuarios/', views.index, name="index"),
    path("usuarios/cadastro/", EmployeeCreateView.as_view(), name="create"),
    path('login/', UserLoginView.as_view(), name="login"), 
    path('usuarios/<str:name>/', views.update, name="update"),
    path('usuarios/<int:id>/delete', views.delete, name="delete"),
    path('logout/', UserLogoutView.as_view(), name="logout"),
]

optimumerp/purchases/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Purchases, PurchasesProduct
from crispy_forms.helper import FormHelper
from suppliers.models import Suppliers
from products.models import Product

class PurchasesForm(forms.ModelForm):
    """
    Formulário para criar ou atualizar um pedido de compra.
    """
    class Meta:
        model = Purchases
        exclude = ["products"]

        labels = {
            "status": "Status",
            "delivery_date": "Data de entrega",
            "total_value": "Valor total",
            "discount": "Desconto(%)",
            "installments": "Parcelas",
            "created_at": "Data de emissão",
            "supplier": "Fornecedor",
            "products": "Produtos",
            "user": "Usuário solicitante"
        }

        widgets = {
            "delivery_date": forms.DateInput(attrs={"type":"date"}, format="%Y-%m-%d"),
            'status': forms.TextInput(attrs={'readonly': 'readonly'}),
            'total_value': forms.TextInput(attrs={'readonly': 'readonly'}),
            'user': forms.TextInput(attrs={'readonly': 'readonly'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["supplier"].queryset = Suppliers.objects.filter(enabled=True)

class PurchasesProductForm(forms.ModelForm):
    """
    Formulário para criar ou atualizar um item de produto em um pedido de compra.
    """
    class Meta:
        model = PurchasesProduct
        fields = "__all__"

        widgets = {
            "unit_value": forms.NumberInput(attrs={"placeholder": "Preço de custo"}),
            "amount": forms.NumberInput(attrs={"placeholder": "Quantidade"}),
            "total_value_product": forms.NumberInput(attrs={"placeholder": "Total", "readonly": "readonly"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields["product"].queryset = Product.objects.filter(enabled=True)
        self.helper.form_show_labels = False

PurchasesProductFormSet = inlineformset_factory(
    Purchases,
    PurchasesProduct,
    form=PurchasesProductForm,
    extra=1,
    can_delete=True,
    max_num=1
)

optimumerp/purchases/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.db import IntegrityError, transaction
from .models import Purchases, PurchasesProduct
from django.http import HttpResponseRedirect, JsonResponse
from products.models import Product, SupplierProduct
from .forms import PurchasesForm, PurchasesProductFormSet
from django.views.decorators.http import require_POST, require_GET
from django.contrib import messages
from transactions.models import Transaction
from .filters import PurchasesFilter
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    """
    Esta função exibe uma lista paginada de todos os pedidos de compra no sistema, permitindo a filtragem e pesquisa.

    Args:
        request (HttpRequest): O objeto HttpRequest que contém os dados da solicitação.

    Returns:
        HttpResponse: Uma resposta HTTP que renderiza a página de listagem de pedidos de compra.
    """

    # Aplicando a paginação
    purchase = Purchases.objects.order_by("-id")
    purchase_filter = PurchasesFilter(request.GET, queryset=purchase)
    paginator = Paginator(purchase_filter.qs.distinct(), 50)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj": page_obj,
        "filter": purchase_filter
    }

    return render(request, "purchases/index.html", context)

def create(request):
    """
    Esta função cria um novo pedido de compra no sistema, permitindo a inclusão de produtos associados.

    Args:
        request (HttpRequest): O objeto HttpRequest que contém os dados da solicitação.

    Returns:
        HttpResponse: Uma resposta HTTP que renderiza a página de criação de pedidos de compra.
    """
    # POST
    if request.method == 'POST':
        form = PurchasesForm(request.POST)

        if form.is_valid():
            purchase = form.save(commit=False)            
            purchase_product_formset = PurchasesProductFormSet(request.POST, instance=purchase)

            if not purchase_product_formset.is_valid():                      
                messages.error(request, "Falha ao cadastrar os produtos do pedido de compra.")
                
                purchase_product_formset = PurchasesProductFormSet(request.POST)
                
                context = { 
                    "form": form, 
                    "purchase_product_formset": purchase_product_formset, 
                }

                return render(request, "purchases/create.html", context)

            if purchase_product_formset.is_valid():
                messages.success(request, "O pedido de compra foi cadastrado com sucesso!")
                purchase.user = request.user
                purchase.save()
                purchase_product_formset.save()
                return redirect("purchases:index")
            
            else:
                messages.error(request, "Falha ao cadastrar o pedido.")
                purchase.delete()
                purchase_product_formset = purchase_product_formset(request.POST)

                context = { 
                    "form": form, 
                    "purchase_product_formset": purchase_product_formset, 
                    }
                
                return render(request, "purchases/create.html", context)
            
        else:
            purchase_product_formset = PurchasesProductFormSet()
            
            context = { 
            "form": form, 
            "purchase_product_formset": purchase_product_formset, 
            }
        
            return render(request, "purchases/create.html", context)    
            
    form = PurchasesForm(initial={'status': "Pendente"})
    purchase_product_formset = PurchasesProductFormSet()

    context = {
        "form": form, 
        "purchase_product_formset": purchase_product_formset,
        }

    return render(request, "purchases/create.html", context)

def get_purchasing_price(request):
    """
    Esta função é acionada via requisição AJAX e retorna o preço de compra de um produto de um fornecedor específico.
    Ela espera receber o ID do produto e o ID do fornecedor como parâmetros na consulta GET.

    Args:
        request (HttpRequest): O objeto HttpRequest que contém os dados da solicitação.

    Returns:
        JsonResponse: Uma resposta JSON contendo o preço de compra do produto. Se a requisição não for uma solicitação AJAX ou se os parâmetros estiverem ausentes, uma mensagem de erro é retornada.
    """
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest' and request.method == 'GET':
        product_id = request.GET.get('product_id')
        supplier_id = request.GET.get('supplier')

        product = SupplierProduct.objects.filter(product_id=product_id, supplier_id=supplier_id).first()
        purchasing = ""
        if product:
            purchasing = product.cost_price
        return JsonResponse({'purchasing': purchasing})
    else:
        return JsonResponse({'error': 'Invalid request'})    

def get_purchasing_price_update(request, id):
    """
    Esta função é usada para retornar o preço de compra de um produto quando o usuário está atualizando um pedido de compra.

    Args:
        request (HttpRequest): O objeto HttpRequest que contém os dados da solicitação.
        id (int): O ID do pedido de compra.

    Returns:
        JsonResponse: Uma resposta JSON contendo o preço de compra do produto.
    """
    value = get_purchasing_price(request)
    return value

def get_purchasing_price_create(request):
    """
    Esta função é usada para retornar o preço de compra de um produto quando o usuário está criando um novo pedido de compra.

    Args:
        request (HttpRequest): O objeto HttpRequest que contém os dados da solicitação.

    Returns:
        JsonResponse: Uma resposta JSON contendo o preço de compra do produto.
    """
    value = get_purchasing_price(request)
    return value

def update(request, id):
    """
    Esta função é responsável por atualizar um pedido de compra existente com base nos dados fornecidos pelo usuário.
    Os dados são enviados através de um formulário POST. Se a atualização for bem-sucedida, o usuário é redirecionado para a página de listagem de pedidos de compra.

    Args:
        request (HttpRequest): O objeto HttpRequest que contém os dados da solicitação.
        id (int): O ID do pedido de compra a ser atualizado.

    Returns:
        HttpResponse: Uma resposta HTTP que redireciona o usuário para a página de listagem de pedidos de compra após a atualização.
    """
    purchase = get_object_or_404(Purchases, pk=id)

    if purchase.status == "Cancelado":
        messages.error(request, f"Erro ao editar o pedido {purchase.id}: Não é possível editar um pedido cancelado.")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

    if purchase.status == "Confirmado":
        messages.error(request, f"Erro ao cancelar pedido {purchase.id}: Não é possível editar um pedido que já foi confirmado.")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

    if request.method == "POST":
        form = PurchasesForm(request.POST, instance=purchase)
        form.fields['supplier'].widget.attrs['readonly'] = 'readonly'
        purchase_product_formset = PurchasesProductFormSet(request.POST, instance=purchase)

        if form.is_valid():
            try:
                form.save()
                if purchase_product_formset.is_valid():
                    purchase_product_formset.save()
                    messages.success(request, "Pedido atualizado com sucesso!")
                    return redirect("purchases:index")
                else:
                    messages.error(request, "Falha ao atualizar o pedido. Verifique os produtos do pedido.")
            except IntegrityError:
                messages.error(request, "Falha ao atualizar o pedido: Não é possível ter o mesmo produto mais de uma vez em um único pedido.")
        else:
            messages.error(request, "Falha ao atualizar o pedido: formulário inválido.")

        purchase_product_formset = PurchasesProductFormSet(instance=purchase)

        context = {
            "form": form,
            "purchase_product_formset": purchase_product_formset
        }

        return render(request, "purchases/update.html", context)

    form = PurchasesForm(instance=purchase)
    form.fields['supplier'].widget.attrs['readonly'] = 'readonly'
    form.fields['user'].widget.attrs['readonly'] = 'readonly'
    purchase_product_formset = PurchasesProductFormSet(instance=purchase)

    context = {
        "form": form,
        "purchase_product_formset": purchase_product_formset
    }

    return render(request, "purchases/update.html", context)

@require_POST
def cancel(request, id):
    """
    Esta função é responsável por cancelar um pedido de compra existente. Se o pedido estiver no estado "Pendente", ele será cancelado com sucesso e uma mensagem de sucesso será exibida. Caso contrário, uma mensagem de erro informando que o pedido não pode ser cancelado será exibida.

    Args:
        request (HttpRequest): O objeto HttpRequest que contém os dados da solicitação.
        id (int): O ID do pedido de compra a ser cancelado.

    Returns:
        HttpResponse: Uma resposta HTTP que redireciona o usuário de volta à página anterior após o cancelamento do pedido.
    """
    purchase = get_object_or_404(Purchases, pk=id)

    if purchase.status == "Cancelado":
        messages.error(request, f"Erro ao cancelar pedido: o pedido {purchase.id} já está cancelado!")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

    if purchase.status == "Confirmado":
        messages.error(request, f"Erro ao cancelar pedido {purchase.id}: Você não pode cancelar um pedido que já foi confirmado!")

optimumerp/purchases/templates/purchases/create.html
{% extends "base.html" %}
{% load static %}
{% block title %}Novo pedido de compra{% endblock  %}
{% block head %}
    <link rel="stylesheet" href="{% static 'purchases/css/createUpdate.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
    <script src="{% static 'purchases/js/createUpdate.js' %}"></script>
{% endblock  %}
{% block page_name %}Novo pedido de compra{% endblock %}
{% block search %}
    {% comment %}Sem search{% endcomment %}
    <div style="height: 38px;"></div>
{% endblock %}
{% block content %}
    <form id="purchases_form" action="{% url "purchases:create" %}" method="POST">
        {% csrf_token %}
        <div class="d-flex create-purchases p-3">
            {% include 'partials/_purchases_form.html' %}
            <div class="d-grid mb-3">
                <button type="button" id="addPurchaseButton" class="btn btn-outline-secondary">Adicionar produto</button>
            </div>
            <div class="d-grid">
                <button id="submitButton" type="submit" class="btn btn-primary btn-lg">Salvar</button>
            </div>
        </div>
    </form>
{% endblock  %}

optimumerp/purchases/templates/purchases/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Pedidos de compra{% endblock  %}
{% block head %}
    <link rel="stylesheet" href="{% static 'purchases/css/index.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
    <script src="{% static 'base/js/index.js' %}"></script>
    <script src="{% static 'purchases/js/index.js' %}"></script>
{% endblock %}
{% block page_name %}Pedidos de compra{% endblock %}
{% block search %}
    {% comment %}Sem search{% endcomment %}
    <div style="height: 38px;"></div>
{% endblock %}
{% block content %}
    <div class="modal fade" id="productsModal" tabindex="-1" aria-labelledby="productsModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="productsModalLabel">Produtos</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Produto</th>
                                <th>Quantidade</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody id="productsTableBody"></tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" tabindex="-2" id="cancelOrderModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Cancelar pedido</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Deseja confirmar a exclusão do pedido? Esta ação não poderá ser desfeita.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Abortar</button>
                    <form id="cancelOrderForm" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Cancelar pedido</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" tabindex="-2" id="finishPurchaseModal" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Receber pedido</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Deseja realmente receber o pedido? Essa ação não poderá ser desfeita.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Abortar</button>
              <form id="finishPurchaseForm" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Receber pedido</button>
              </form>
            </div>
          </div>
        </div>
      </div>

    <div class="row container-fluid">
        <div class="col-md-2">
        <a href="{% url 'purchases:create' %}" title="Novo pedido de compra" class="btn btn-success">
            <i class="bi bi-plus"></i>
            Novo
        </a>
        </div>
    </div>

    <div class="row d-flex mt-2 container-fluid">
        <div class="col-md-3">
          {% include 'partials/_filter.html' with main_page="purchases:index" %}
        </div>

        <div class="table-responsive bg-white p-2 col-md-9 rounded" style="height:80vh">
            <table class="table table-borderless table-hover table-sm table-color">
                <thead class="table-border">
                    <tr>
                        <th>Ações</th>
                        <th>ID</th>
                        <th>Status</th>
                        <th>Fornecedor</th>
                        <th>Emissão</th>
                        <th>Comprador</th>
                        <th>Entrega</th>
                        <th>Valor total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for purchase in page_obj %}
                        <tr>
                            <td class="d-flex gap-1">
                                {% if purchase.status == "Pendente" %}
                                    <button 
                                        data-order-id="{% url 'purchases:finish_order' purchase.id %}" 
                                        data-bs-toggle="modal" 
                                        data-bs-target="#finishPurchaseModal" 
                                        type="submit" 
                                        class="btn btn-success btn-sm" title="Receber">
                                        <i class="bi bi-check"></i>
                                    </button>
                                {% elif purchase.status == "Confirmado" %}
                                    <a 
                                        href="#" 
                                        class="btn btn-success btn-sm disabled"
                                        title="Confirmado">
                                        <i class="bi bi-check"></i>
                                    </a>
                                {% elif purchase.status == "Cancelado" %}
                                    <a 
                                        href="#" 
                                        class="btn btn-success btn-sm disabled">
                                        <i class="bi bi-x"></i>
                                    </a>
                                {% endif %}
                                <button 
                                    data-url="{% url 'purchases:products' purchase.id %}" 
                                    title="Produtos do pedido" 
                                    class="btn btn-primary btn-sm" 
                                    data-bs-toggle="modal" 
                                    data-bs-target="#productsModal">
                                    <i class="bi bi-dice-3"></i>
                                </button>
                                <a
                                    href="{% url 'purchases:update' purchase.id %}" 
                                    class="btn btn-warning btn-sm {% if purchase.status == "Cancelado" or purchase.status == "Confirmado" %}disabled{% endif %}"
                                    title="Editar fornecedor">
                                    <i class="bi bi-pencil"></i>
                                </a>
                                <button 
                                    data-order-id="{% url 'purchases:cancel' purchase.id %}"
                                    {% if purchase.status == "Cancelado" or purchase.status == "Confirmado" %}disabled{% endif %} 
                                    data-bs-toggle="modal" 
                                    data-bs-target="#cancelOrderModal" 
                                    type="submit" 
                                    class="btn btn-danger btn-sm cancel-order-btn" 
                                    title="Cancelar pedido">
                                    <i class="bi bi-trash"></i>
                                </button>
                            </td>
                            <td>{{ purchase.id }}</td>
                            <td>{{ purchase.status }}</td>
                            <td>{{ purchase.supplier|title }}</td>
                            <td>{{ purchase.created_at|date:'SHORT_DATE_FORMAT' }}</td>
                            <td>{{ purchase.user }}</td>
                            <td>{{ purchase.delivery_date|date:'SHORT_DATE_FORMAT' }}{% if not purchase.delivery_date %}A definir{% endif %}</td>
                            <td>R${{ purchase.total_value }}</td>
                        </tr>
                
                        {% empty %}
                        <tr>
                            <td colspan="8" class="text-center">Nenhum pedido de compra cadastrado</td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% include "partials/_paginator.html" %}
    </div>
    {% for order in orders %}
        {{order.supplier}}
    {% endfor %}
{% endblock  %}

optimumerp/purchases/templates/purchases/update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Editar pedido de compra{% endblock  %}
{% block head %}
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
    <script src="{% static 'purchases/js/createUpdate.js' %}"></script>
    <link rel="stylesheet" href="{% static 'purchases/css/style.css' %}">
{% endblock  %}
{% block page_name %}Editar pedido de compra{% endblock %}
{% block search %}
    {% comment %}Sem search{% endcomment %}
    <div style="height: 38px;"></div>
{% endblock %}
{% block content %}
    <form id="purchases_form" method="POST">
        {% csrf_token %}
        <div class="d-flex create-purchases p-3">
            {% include 'partials/_purchases_form.html' %}
            <div class="d-grid mb-3">
                <button type="button" id="addPurchaseButton" class="btn btn-outline-secondary">Adicionar produto</button>
            </div>
            <div class="d-grid">
                <button id="submitButton" type="submit" class="btn btn-primary btn-lg">Salvar</button>
            </div>
        </div>
    </form>
{% endblock  %}