optimumerp/optimumerp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedores/', include('suppliers.urls')),
    path('produtos/', include("products.urls")),
    path('transacoes/', include("transactions.urls")),
    path('estoque/', include("inventory.urls")),
    path("clientes/", include("clients.urls")),
    path("pedidos-de-venda/", include("sales_order.urls")),
    path('', include('users.urls')),
    path('nota-fiscal/', include('invoices.urls')),
    path("pedidos-de-compras/", include("purchases.urls")),
    path('empresa/', include("company.urls")),
    path('dashboard/', include('dashboard.urls')),
    path('categorias/', include("categories.urls"))
]

optimumerp/users/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views
from .views import UserLoginView, UserLogoutView, EmployeeCreateView

app_name = 'users'
urlpatterns = [
    path("", RedirectView.as_view(url="/login/", permanent=True)),
    path('usuarios/', views.index, name="index"),
    path("usuarios/cadastro/", EmployeeCreateView.as_view(), name="create"),
    path('login/', UserLoginView.as_view(), name="login"), 
    path('usuarios/<str:name>/', views.update, name="update"),
    path('usuarios/<int:id>/delete', views.delete, name="delete"),
    path('logout/', UserLogoutView.as_view(), name="logout"),
]

optimumerp/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group

class UserManager(BaseUserManager):
    """
    Gerenciador de usuário personalizado onde os e-mails são os identificadores exclusivos para autenticação,
    ao invés de nomes de usuário.

    Métodos:
        create_user: Cria e salva um usuário com o e-mail, nome e senha fornecidos.
        create_superuser: Cria e salva um superusuário com o e-mail, nome e senha fornecidos.
    """
    def create_user(self, email, name, password=None):
        """
        Cria e salva um usuário com o e-mail, nome e senha fornecidos.

        Args:
            email (str): E-mail do usuário.
            name (str): Nome do usuário.
            password (str): Senha do usuário.

        Returns:
            User: O objeto de usuário recém-criado.

        Raises:
            ValueError: Se nenhum e-mail for fornecido.
        """
        if not email:
            raise ValueError("Por favor, informe um e-mail.")
        
        user = self.model(email=self.normalize_email(email), name=name,)
        user.set_password(password)
        user.save(using=self._db)
        return user
        
    def create_superuser(self, email, name, password=None):
        """
        Cria e salva um superusuário com o e-mail, nome e senha fornecidos.

        Args:
            email (str): E-mail do superusuário.
            name (str): Nome do superusuário.
            password (str): Senha do superusuário.

        Returns:
            User: O objeto de superusuário recém-criado.
        """
        user = self.create_user(email, password=password, name=name)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """
    Modelo de usuário personalizado onde os e-mails são os identificadores exclusivos para autenticação,
    ao invés de nomes de usuário.

    Atributos:
        email (str): E-mail do usuário (único).
        name (str): Nome do usuário.
        password (str): Senha do usuário.
        is_staff (bool): Indica se o usuário pode acessar a interface de administração.
        is_active (bool): Indica se o usuário está ativo.

    Métodos:
        __str__: Retorna uma representação de string do usuário.
    """
    email = models.EmailField("E-mail", unique=True)
    name = models.CharField("Nome", max_length=255)
    password = models.CharField("Senha", max_length=255)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField("Ativo", default=True)

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["name"]

    objects = UserManager()

    def __str__(self):
        """
        Retorna uma representação de string do usuário.
        """
        return self.name
    
    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"


class Employee(models.Model):
    """
    Modelo que representa um funcionário associado a um usuário.

    Atributos:
        group (Group): Grupo ao qual o funcionário está associado.
        user (User): Usuário associado ao funcionário.

    Métodos:
        __str__: Retorna uma representação de string do funcionário.
    """
    DEFAULT_GROUP_ID = 1
    group = models.ForeignKey(Group, on_delete=models.CASCADE, default=DEFAULT_GROUP_ID)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        """
        Retorna uma representação de string do funcionário.
        """
        return self.user.name if self.user else "Employee"

    class Meta:
        verbose_name = "Funcionário"
        verbose_name_plural = "Funcionários"

optimumerp/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.models import Group
from .models import Employee
from django.db import transaction

User = get_user_model()

class UserCreationForm(forms.ModelForm):
    """
    Formulário para criar um novo usuário.

    Atributos:
        password1 (str): Campo para a senha do usuário.
        password2 (str): Campo para a confirmação da senha do usuário.

    Métodos:
        clean_password: Valida se as senhas digitadas são iguais.
        save: Salva o usuário no banco de dados com a senha criptografada.
    """
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput())
    password2 = forms.CharField(label="Password confirmation", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["email", "name"]

    def clean_password(self):
        """
        Verifica se as senhas digitadas nos campos 'password1' e 'password2' são iguais.
        """
        password1 = self.cleaned_data.get["password1"]
        password2 = self.cleaned_data.get["password2"]
        if password1 != password2 and password1 != password2:
            raise ValidationError("As senhas não combinam.")
        return password2
    
    def save(self, commit=True):
        """
        Salva o usuário com a senha criptografada.

        Args:
            commit (bool): Define se a operação de salvamento no banco de dados deve ser executada imediatamente.

        Returns:
            User: O objeto de usuário recém-criado.
        """
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
    

class UserChangeForm(forms.ModelForm):
    """
    Formulário para alterar os dados de um usuário.

    Atributos:
        password (ReadOnlyPasswordHashField): Campo somente leitura para a senha do usuário.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ["email", "password", "name", "is_active", "is_superuser"]


class UserForm(forms.ModelForm):
    """
    Formulário para editar os dados de um usuário.

    Métodos:
        save: Salva o usuário, atribui automaticamente um grupo padrão e cria um novo funcionário associado.

    """

    class Meta:
        model = User
        fields = ["name", "email", "password", "is_active"]
        widgets = {
            "password": forms.PasswordInput()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.default_group = Group.objects.get(name='Employee')

    @transaction.atomic
    def save(self, commit=True):
        """
        Salva o usuário, atribui automaticamente um grupo padrão e cria um novo funcionário associado.

        Args:
            commit (bool): Define se a operação de salvamento no banco de dados deve ser executada imediatamente.

        Returns:
            User: O objeto de usuário salvo.
        """
        password = self.cleaned_data.get("password")
        user = super().save(commit=False)

        # Hash da senha
        if password:
            user.set_password(password)
        if commit:
            user.save()
            # Atribui automaticamente o grupo padrão ao usuário
            user.groups.add(self.default_group)
            # Cria um novo funcionário (Employee) associado ao usuário e ao grupo padrão
            employee = Employee.objects.create(user=user, group=self.default_group)
            employee.save()
        return user

optimumerp/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import UserForm
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import get_user_model

User = get_user_model()

@login_required
def index(request):
    """
    Exibe uma lista de todos os usuários cadastrados.

    Returns:
        HttpResponse: Renderiza a página HTML com a lista de usuários.
    """
    users = User.objects.all().order_by('-id')
    context = {
        'users': users
    }
    return render(request, 'users/index.html', context)


class EmployeeCreateView(CreateView):
    """
    View para criar um novo usuário (funcionário).

    Atributos:
        model (Model): O modelo do banco de dados para criar o usuário.
        form_class (Form): O formulário para criar o usuário.
        template_name (str): O nome do template HTML para renderizar a página.
        success_url (str): A URL para redirecionar após a criação bem-sucedida do usuário.
    """
    model = User
    form_class = UserForm
    template_name = "users/create.html"
    success_url = reverse_lazy("users:index")


def update(request, name):
    """
    View para atualizar as informações de um usuário existente.

    Args:
        request (HttpRequest): O objeto de requisição HTTP.
        name (str): O nome do usuário a ser atualizado.

    Returns:
        HttpResponse: Renderiza o formulário de atualização do usuário.
    """
    user = User.objects.get(name=name)

    if request.method == 'POST':
        form = UserForm(request.POST, instance=user)

        if form.is_valid():
            form.save()
            messages.success(request, "Usuário atualizado com sucesso!")
            return redirect("users:index")
        else:
            context = {
                "form": form,
            }
            return render(request, "update.html", context)
        
    else:
        form = UserForm(instance=user)
        context = {
            "form": form,
        }
    return render(request, 'users/update.html', context)


def delete(request, id):
    """
    View para excluir um usuário existente.

    Args:
        request (HttpRequest): O objeto de requisição HTTP.
        id (int): O ID do usuário a ser excluído.

    Returns:
        HttpResponseRedirect: Redireciona para a página de listagem de usuários após a exclusão.
    """
    user = get_object_or_404(User, id=id)
    user.delete()
    return redirect("users:index")


class UserLoginView(LoginView):
    """
    View para login de usuários.

    Atributos:
        template_name (str): O nome do template HTML para renderizar a página de login.
        redirect_authenticated_user (bool): Define se os usuários autenticados serão redirecionados automaticamente.
        next_page (str): A URL para redirecionar após o login bem-sucedido.
    """
    template_name = 'users/login.html'
    redirect_authenticated_user = True
    next_page = "dashboard:index"
    
    
class UserLogoutView(LogoutView):
    """
    View para logout de usuários.

    Atributos:
        next_page (str): A URL para redirecionar após o logout bem-sucedido.
    """
    next_page = "users:login"

optimumerp/users/templates/users/create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Cadastro de Usuários{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'user/css/createUpdate.css' %}">

    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
{% endblock %}

{% block page_name %}
    Cadastro de Usuário
{% endblock %}

{% block search %}
  {% comment %}Sem search{% endcomment %}
  <div style="height: 38px;"></div>
{% endblock %}

{% block content %}
    <form action="{{ form_action }}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="d-grid">
            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
        </div>
    </form>
{% endblock %}

optimumerp/users/templates/users/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Usuários{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'user/css/index.css' %}">

    <script src="{% static 'user/js/index.js' %}"></script>
{% endblock %}

{% block page_name %}Usuários{% endblock %}

{% block search %}
  {% comment %}Sem search{% endcomment %}
  <div style="height: 38px;"></div>
{% endblock %}

{% block content %}

<div class="row container-fluid">
    <div class="col-md-2">
        <a href="{% url "users:create" %}" title="Cadastrar um novo usuário" class="btn btn-success">
            <i class="bi bi-plus"></i>
            Novo
        </a>
    </div>
</div>

<div class="row d-flex mt-2 mx-0 container-fluid">

    <div class="table-responsive bg-white col p-2 rounded">
        <table class="table table-borderless table-hover table-sm table-color">
            <thead class="table-border">
                <tr>
                    <th>Ações</th>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Ativo</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td class="d-flex gap-1 actions">
                            <a href="{% url 'users:update' user.name %}" class="btn btn-warning btn-sm" title="editar usuário"><i class="bi bi-pencil"></i></a>
                            <form action="{% url 'users:delete' user.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm" title="remover usuário"><i class="bi bi-trash"></i></button>
                            </form>
                        </td>
                        <td>{{ user.id }}</td>
                        <td>{{ user.name|title }}</td>
                        <td>{{ user.email }}</td>
                        <td><input {% if user.is_active %}checked{% endif %} type="checkbox" class="form-check-input"></td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td class="text-center">Nenhum usuário cadastrado.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

optimumerp/users/templates/users/login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Optimum - Login</title>

    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'base/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'base/js/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'user/js/login.js' %}"></script>

    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'user/css/login.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anton&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Quicksand:wght@700&display=swap" rel="stylesheet">
</head>
<body class="d-flex flex-column align-items-center bg-dark text-light">
    <div class="position-absolute top-50 start-50 translate-middle">
        <div class="img">
           <img src="{% static 'base/img/optimum_logo.png' %}" alt="Logo Optimum" height="100px"> 
        </div>
        <div class="p-4 mb-3 bg-login rounded d-flex flex-column justify-content-center">
            <form action="{% url 'users:login' %}" method="post" class="d-flex flex-column p-5" novalidate>
                {% csrf_token %}
                <h3>Faça seu login</h3>
                <div class="d-flex">
                    <i class="bi bi-person"></i>
                    <i class="bi bi-lock"></i>
                    <button type="button" id="btnPassword" class="btn btn-position"><i class="bi bi-eye-slash" id="eyeIcon"></i></button>
                </div>
                <div id="div_id_username" class="mb-1">
                    <label for="id_username" class="form-label requiredField"></label>
                    <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" class="textinput form-control bg-dark text-light border border-0 input {% if form.username.errors %}is-invalid{% endif %}" required="" id="id_username">
                </div>
                <div id="div_id_password" class="mb-5">
                    <label for="id_password" class="form-label requiredField"></label>
                    <input type="password" name="password" autocomplete="current-password" class="passwordinput form-control bg-dark text-light border border-0 input {% if form.username.errors %}is-invalid{% endif %}" required="" id="id_password">
                </div>
                <input type="hidden" name="next" value={{request.GET.next}}>
                <button type="submit" class="btn btn-dark mt-3 btn-submit">ENTRAR</button>
            </form>
        </div>
        <h1 class="mt-3">Seu futuro começa aqui!</h1>
    </div>
    {% if form.errors %}
    <div class="alert alert-danger sticky" role="alert">
        {% if form.username.errors and form.password.errors %}
            Usuário e senha incorretos
        {% elif form.username.errors %}
            Usuário incorreto
        {% elif form.password.errors %}
            Senha incorreta
        {% else %}
            Entre com um usuário cadastrado
        {% endif %}
    </div>
    {% endif %}
</body>
</html>

optimumerp/users/templates/users/update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Atualização de Usuários{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'user/css/createUpdate.css' %}">

    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
{% endblock %}

{% block page_name %}
    Atualização de Usuário
{% endblock %}

{% block search %}
  {% comment %}Sem search{% endcomment %}
  <div style="height: 38px;"></div>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-grid">
            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
        </div>
    </form>
{% endblock %}