optimumerp/optimumerp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedores/', include('suppliers.urls')),
    path('produtos/', include("products.urls")),
    path('transacoes/', include("transactions.urls")),
    path('estoque/', include("inventory.urls")),
    path("clientes/", include("clients.urls")),
    path("pedidos-de-venda/", include("sales_order.urls")),
    path('', include('users.urls')),
    path('nota-fiscal/', include('invoices.urls')),
    path("pedidos-de-compras/", include("purchases.urls")),
    path('empresa/', include("company.urls")),
    path('dashboard/', include('dashboard.urls')),
    path('categorias/', include("categories.urls"))
]

optimumerp/products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path("", views.index, name="index"),
    # path("search", views.search, name="search"),
    path("cadastro", views.create, name="create"),
    path("<slug:slug>", views.update, name="update"),
    path("<int:id>/toggle_enabled", views.toggle_enabled, name="toggle_enabled"),
    path("<int:id>/delete", views.delete, name="delete"),
    path("<int:id>/suppliers/", views.get_suppliers_from_product, name="suppliers"),
    path("<int:id>/delete_supplier", views.delete_supplier_from_product, name="delete_supplier"),
]

optimumerp/users/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views
from .views import UserLoginView, UserLogoutView, EmployeeCreateView

app_name = 'users'
urlpatterns = [
    path("", RedirectView.as_view(url="/login/", permanent=True)),
    path('usuarios/', views.index, name="index"),
    path("usuarios/cadastro/", EmployeeCreateView.as_view(), name="create"),
    path('login/', UserLoginView.as_view(), name="login"), 
    path('usuarios/<str:name>/', views.update, name="update"),
    path('usuarios/<int:id>/delete', views.delete, name="delete"),
    path('logout/', UserLogoutView.as_view(), name="logout"),
]

optimumerp/products/forms.py
from django import forms

from suppliers.models import Suppliers
from .models import Product, SupplierProduct
from crispy_forms.helper import FormHelper


class ProductForm(forms.ModelForm):
    """
    Formulário para adicionar ou atualizar informações de um produto.
    """
    class Meta:
        model = Product
        exclude = ["slug", "is_perishable", "supplier"]

        labels = {
            "name": "Nome",
            "description": "Descrição",
            "category": "Categoria",
            "sale_price": "Preço de venda",
            "cst": "Código de situação tributária (CST)",
            "minimum_stock": "Estoque mínimo",
            "unit_of_measurement": "Unidade de medida",
            "expiration_date": "Data de expiração",
            "enabled": "Ativo"
        }

        error_messages = {
            "name": {
                "unique": "Já existe um produto cadastrado com esse nome",
                "required": "O campo nome é obrigatório"
            },
            "description": {
                "required": "O campo descrição é obrigatório"
            },
            "sale_price": {
                "required": "O campo preço de venda é obrigatório",
            },
            "unit_of_measurement": {
                "required": "O campo de unidade de medida é obrigatório"
            },
            "cst": {
                "required": "O campo de CST é obrigatório"
            }
        }
        
        widgets = {
            "expiration_date": forms.DateInput(attrs={"type":"date"}, format="%Y-%m-%d")
        }


class SupplierProductForm(forms.ModelForm):
    """
    Formulário para adicionar ou atualizar informações de fornecedores de um produto.
    """    
    
    class Meta:
        model = SupplierProduct
        fields = "__all__"
        # exclude = ["product"]
        widgets = {
            "cost_price": forms.NumberInput(attrs={"placeholder": "Preço de custo"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields["supplier"].queryset = Suppliers.objects.filter(enabled=True)
        self.helper.form_show_labels = False

SupplierProductFormSet = forms.inlineformset_factory(
    Product,
    SupplierProduct,
    form=SupplierProductForm,
    extra=1,
    can_delete=True,
    max_num=1
)

optimumerp/products/views.py
from django.shortcuts import render
from .models import Product, SupplierProduct
from inventory.models import Inventory
from django.db import IntegrityError
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.http import require_POST, require_GET
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import messages
from .forms import ProductForm
from .forms import SupplierProductFormSet
from sales_order.models import SalesOrderProduct
from inventory.models import Inventory
from django.db.models import Count
from .filters import ProductFilter
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    """

    Esta função exibe uma lista paginada de todos os produtos no sistema, permitindo a filtragem por meio de parâmetros de consulta.
    
    Args:
        request (HttpRequest): O objeto HttpRequest que contém os dados da solicitação.

    Returns:
        HttpResponse: Uma resposta HTTP que renderiza a página de listagem de produtos.
    """    
    # Obtendo todos os produtos e a quantidade em estoque
    products = Product.objects.order_by("-id")
    inventory_quantity = Inventory.objects.all()

    # Aplicando filtros de pesquisa
    product_filter = ProductFilter(request.GET, queryset=products)

    # Aplicando a paginação
    paginator = Paginator(product_filter.qs, 50)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "products": page_obj,
        "inventory_quantity": inventory_quantity,
        'filter': product_filter
        }
    
    return render(request, "products/index.html", context)

def create(request):
    """

    Esta função exibe o formulário de criação de um novo produto e processa a submissão do formulário. 
    Após a submissão bem-sucedida do formulário, o produto é salvo no banco de dados e um registro é criado na tabela Inventory.

    Args:
        request (HttpRequest): O objeto HttpRequest que contém os dados da solicitação.

    Returns:
        HttpResponse: Uma resposta HTTP que renderiza a página de criação de produtos ou redireciona para a página de listagem de produtos após a criação bem-sucedida.
    """    
    form_action = reverse("products:create")

    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
                product = form.save() # Salva o produto no banco de dados
                try:
                    Inventory.objects.create(product=product, quantity=0) # Cria um registro na tabela Inventory
                except:
                    messages.error(request, "Falha ao cadastrar o produto no estoque")
                    product.delete() # Deleta o produto caso não crie o registro na tabela Inventory

                    context = { 
                        "form": form, 
                        "supplier_product_formset": supplier_product_formset, 
                        "form_action": form_action,
                        }
                    
                    return render(request, "products/create.html", context)
                
                supplier_product_formset = SupplierProductFormSet(request.POST, instance=product)
                
                if not supplier_product_formset.is_valid():     
                    # Se o formulário de fornecedores não for válido, exclui o produto                 
                    messages.error(request, "Falha ao cadastrar os fornecedores do produto")
                    product.delete()
                    
                    supplier_product_formset = SupplierProductFormSet(request.POST)
            
                    context = { 
                        "form": form, 
                        "supplier_product_formset": supplier_product_formset, 
                        "form_action": form_action,
                        }
                    
                    return render(request, "products/create.html", context)
                
                supplier_product_formset.save()

                return redirect("products:index")

    # GET
    form = ProductForm()
    supplier_product_formset = SupplierProductFormSet()

    context = {
        "form": form, 
        "form_action": form_action,
        "supplier_product_formset": supplier_product_formset
        }

    return render(request, "products/create.html", context)

def update(request, slug):
    """
    Esta função exibe o formulário de atualização de um produto existente e processa a submissão do formulário. 
    Após a submissão bem-sucedida do formulário, o produto é atualizado no banco de dados.

    Args:
        request (HttpRequest): O objeto HttpRequest que contém os dados da solicitação.
        slug (str): O slug único do produto a ser atualizado.

    Returns:
        HttpResponse: Uma resposta HTTP que renderiza o formulário de atualização de produto ou redireciona para a página de listagem de produtos após a atualização bem-sucedida.
    """    
    product = get_object_or_404(Product, slug=slug)
    form_action = reverse("products:update", args=(slug,))

    # POST
    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        supplier_product_formset = SupplierProductFormSet(request.POST, instance=product)
        
        if form.is_valid():
            if supplier_product_formset.is_valid():
                try:
                    supplier_product_formset.save()
                    messages.success(request, "Produto atualizado com sucesso!")

                except IntegrityError:
                    messages.error(request, "Existem fornecedores duplicados.")
                    context = {
                        "form_action": form_action,
                        "supplier_product_formset": supplier_product_formset,
                        "form": form
                    }

                    return render(request, "products/create.html", context)
            
            form.save()
            print(supplier_product_formset)
            # messages.success(request, "Produto atualizado com sucesso!")
            return redirect("products:index")
        
        messages.error(request, "Não foi possível atualizar o produto.")
        context = {
            "form_action": form_action,
            "form": form
        }

        return render(request, "products/create.html", context)
    
    # GET
    form =  ProductForm(instance=product)
    supplier_product_formset = SupplierProductFormSet(instance=product)
    context = {
        "form_action": form_action,
        "form": form,
        "supplier_product_formset": supplier_product_formset,
    }

    return render(request, "products/create.html", context)

@require_POST
def delete(request, id):
    """
    Esta função exclui um produto do banco de dados se não estiver associado a nenhum pedido de venda ou transação de estoque.

    Args:
        request (HttpRequest): O objeto HttpRequest que contém os dados da solicitação.
        id (int): O ID do produto a ser excluído.

    Returns:
        HttpResponseRedirect: Redireciona o usuário de volta à página anterior após a exclusão bem-sucedida do produto.
    """    
    product = get_object_or_404(Product, pk=id)

    # Verifica se o produto está associado a pedidos de vendas pendentes
    sales_order_count = SalesOrderProduct.objects.filter(product=product).aggregate(count=Count('id'))['count']
    if sales_order_count > 0:
        messages.error(request, f"Não é possível excluir um produto que está associado a um pedido de vendas.")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

    # Verifica se o produto está associado a transações de estoque
    transactions_count = Inventory.objects.filter(product=product).aggregate(count=Count('id'))['count']
    if transactions_count > 0:
        messages.error(request, f"Não foi possível excluir o produto, pois o mesmo já possui transações. Considere inativá-lo.")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    
    # Exclui o produto do banco de dados    
    product.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

@require_POST
def toggle_enabled(request, id):
    """
    Esta função alterna o status de ativação de um produto entre ativo e inativo.

    Args:
        request (HttpRequest): O objeto HttpRequest que contém os dados da solicitação.
        id (int): O ID do produto a ter o status de ativação alterado.

    Returns:
        JsonResponse: Retorna uma resposta JSON indicando o sucesso da operação.
    """    
    product = get_object_or_404(Product, pk=id)

    # Verifica se o produto está associado a pedidos de vendas pendentes
    pending_sale_order = SalesOrderProduct.objects.filter(product=product, sale_order__status="Pendente").aggregate(count=Count('id'))['count']
    if pending_sale_order > 0:
        messages.error(request, f"Não é possível inativar um produto que contém um pedido de vendas pendente.")
        return JsonResponse({ "message": "error" })
    
    # Alterna o status de ativação do produto
    product.enabled = not product.enabled
    product.save()
    
    return JsonResponse({ "message": "success" })

@require_POST
def delete_supplier_from_product(request, id):
    """
    Esta função exclui um registro de fornecedor associado a um produto do banco de dados.

    Args:
        request (HttpRequest): O objeto HttpRequest que contém os dados da solicitação.
        id (int): O ID do registro do fornecedor a ser excluído.

    Returns:
        JsonResponse: Retorna uma resposta JSON indicando o sucesso da operação.
    """
    supplier_product = get_object_or_404(SupplierProduct, pk=id)
    supplier_product.delete()

    return JsonResponse({"message": "success"})

@require_GET

optimumerp/products/templates/products/create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Cadastro de produtos{% endblock  %}
{% block head %}
    <link rel="stylesheet" href="{% static 'products/css/createUpdate.css' %}">

    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
    <script src="{% static 'products/js/createUpdate.js' %}"></script>
{% endblock  %}

{% block search %}
  {% comment %}Sem search{% endcomment %}
  <div style="height: 38px;"></div>
{% endblock %}

{% block page_name %}
    {% if form_action == "/produtos/cadastro" %}
        Cadastro de produtos
    {% else %}
        Edição de produto
    {% endif %}
{% endblock %}

{% block content %}
    {% with create_url="/produtos/cadastro" %}
        
        <form action="{{ form_action }}" novalidate method="POST">
            {% csrf_token %}

            <div class="d-flex create-products p-3">
                {% include 'partials/_products_form.html' %}
                <div class="d-grid mb-3">
                    <button type="button" id="addSupplierButton" class="btn btn-outline-secondary">Adicionar fornecedor</button>
                </div>
                <div class="d-grid">
                    <button id="submitButton" type="submit" class="btn btn-primary btn-lg">Salvar</button>
                </div>
            </div>
        </form>
    {% endwith %}
{% endblock  %}

optimumerp/products/templates/products/index.html
{% extends "base.html" %}
{% load static %}
{% load quantity_filter %}

{% block title %}Produtos{% endblock  %}

{% block head %}
<link rel="stylesheet" href="{% static 'products/css/index.css' %}">

<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
<script src="{% static 'base/js/index.js' %}"></script>
<script src="{% static 'products/js/index.js' %}"></script>
{% endblock  %}

{% block page_name %}Produtos{% endblock %}

{% block search %}
  {% comment %}Sem search{% endcomment %}
  <div style="height: 38px;"></div>
{% endblock %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="suppliersModal" tabindex="-1" aria-labelledby="suppliersModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="suppliersModalLabel">Fornecedores</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Preço de custo</th>
                    </tr>
                    </thead>
                    <tbody id="suppliersTableBody">

                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<div class="row container-fluid">
    <div class="col-md-2">
        <a 
        href="{% url 'products:create' %}"
        title="Cadastrar novo produto"
        class="btn btn-success">
            <i class="bi bi-plus"></i>
            Novo
        </a>
    </div>
</div>

<div class="row d-flex mt-2 container-fluid">

    {% comment %} FILTRO AO LADO DO USUARIO {% endcomment %}
    {% comment %} Filtro {% endcomment %}
    {% comment %} {% include "partials/_search_filter.html" with search_value="products:search" %} {% endcomment %}

    <div class="col-md-3">
        {% include "partials/_filter.html" with main_page="products:index" %}
      </div>

    {% comment %} Tabela de produtos {% endcomment %}
    <div class="table-responsive bg-white p-2 col-md-9 rounded" style="height:80vh">
        <table class="table table-borderless table-hover table-sm table-color">
            <thead class="table-border">
                <tr>
                    <th>Ações</th>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Categoria</th>
                    <th>Estoque</th>
                    <th>Unidade</th>
                    <th>Preço de venda</th>
                    <th>Expiração</th>
                    <th>Ativo</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td class="d-flex gap-1">
                        <button data-url="{% url 'products:suppliers' product.id %}" title="Fornecedores do produto" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#suppliersModal">
                            <i class="bi bi-box"></i>
                        </button>
                        <a href="{% url 'products:update' product.slug %}" class="btn btn-warning btn-sm" title="Editar produto">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <form method="post" action="{% url 'products:delete' product.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm" title="Remover produto">
                                <i class="bi bi-trash"></i>
                            </button>
                        </form>
                    </td>
                    <td>{{ product.id }}</td>
                    <td title="{{ product.name }}">{{ product.name|title|truncatechars:20 }}</td>
                    <td title="{{ product.description }}">{{ product.description|truncatechars:20 }}</td>
                    <td title="{{ product.category }}">{{ product.category|truncatechars:15 }}</td>
                    <td>
                        {% for inventory_product in inventory_quantity %}
                            {% if inventory_product.product == product %}
                                {{ inventory_product.quantity|format_quantity }}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {{ product.unit_of_measurement }}
                    </td>
                    <td>R${{ product.sale_price }}</td>
                    <td> 
                        {% if product.expiration_date %}
                            {{ product.expiration_date|date:"SHORT_DATE_FORMAT" }}
                        {% else %}
                            Não perecível
                        {% endif %}
                    </td>
                    <td>
                        <input type="checkbox" class="form-check-input" {% if product.enabled %}checked{% endif %} data-url={% url 'products:toggle_enabled' product.id %}>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="10" class="text=center">Nenhum produto cadastrado</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
            {% comment %} Paginação {% endcomment %}
            {% if products.paginator.num_pages > 1 %}
            <nav aria-label="Paginação da página">
                <ul class="pagination justify-content-end">
                    {% if products.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ products.previous_page_number }}" class="page-link" aria-label="Anterior">&laquo;</a>
                    </li>
                    {% endif %}
                    <li class="page-item active">
                        <span class="page-link">{{ products.number }}</span>
                    </li>
                    {% if products.has_next %}
                    <li class="page-item">
                        <a href="?page={{ products.next_page_number }}" class="page-link" aria-label="Próximo">&raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
</div>

{% endblock  %}

optimumerp/products/templates/products/update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Edição de produtos{% endblock  %}
{% block head %}
    <link rel="stylesheet" href="{% static 'products/css/createUpdate.css' %}">

    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
    <script src="{% static 'products/js/createUpdate.js' %}"></script>
{% endblock  %}

{% block page_name %}
        Edição de produtos
{% endblock %}

{% block search %}
  {% comment %}Sem search{% endcomment %}
  <div style="height: 38px;"></div>
{% endblock %}

{% block content %}
        <form id="products_form" method="POST">
            {% csrf_token %}

            <div class="d-flex create-products p-3">
                {% include 'partials/_products_form.html' %}
                <div class="d-grid mb-3">
                    <button type="button" id="addSupplierButton" class="btn btn-outline-secondary">Adicionar fornecedor</button>
                </div>
                <div class="d-grid">
                    <button id="submitButton" type="submit" class="btn btn-primary btn-lg">Salvar</button>
                </div>
            </div>
        </form>
{% endblock  %}